language: node_js
cache: npm
branches:
  only:
    - master
notifications:
  email: false
node_js:
  # - '12'
  - '11'
  - '10'
before_script:
  - npm prune
install:
  - npm install
script:
  - npm run test
  - npm run publish:major
  - npm run start
  - npm run start:ipfs:template
  - npm run start:app
  - npm run start:http
  - npm run publish:major
  - npm run versions